### ISSUE TITLE
seems like something is missing

### ISSUE THREAD

**Issue by typemytype** [robotools/extractor#33]
got this error @jenskutilek 

```console
extractor/formats/opentype.py", line 137, in extractMaxpValues
    "maxFunctionDefs": maxp.maxFunctionDefs,
AttributeError: 'table__m_a_x_p' object has no attribute 'maxFunctionDefs'
```

**Comment by jenskutilek** [comment]
8-) I was too much TrueType-focused, of course OTF uses a different maxp table. Will fix.

**Comment by typemytype** [comment]
didnt had time to investigate

maybe add a otf,  woff, pfa, pfb test files

the vfb files are nice since extractor can extract them if vfb2ufo is installed locally
but for tests it is not usable, use the flag `haveVfb2ufo` while running a test

**Comment by jenskutilek** [comment]
Yeah, I just added the VFB for completeness to see where the test TTF comes from. Plex is one of the few fully-hinted TTFs freely available including hinted source.

**Comment by jenskutilek** [comment]
Fixed it and also added a simple roundtrip test script.
