### ISSUE TITLE
Add support for .ufoz (UFO compressed ZIP format)

### ISSUE THREAD

**Issue by NightFurySL2001** [robotools/extractor#50]
According to [UFO 3 Specification](https://unifiedfontobject.org/versions/ufo3/), a UFO folder may be compressed into a ZIP format file with the extension `.ufoz`. [Files bigger than ~4GB should use the ZIP64 format.](https://en.wikipedia.org/wiki/ZIP_(file_format)#Limits)

This will be a very good addition as CJK fonts that need to go up on Google Fonts has tens of thousands of glyphs that uploading the UFO folder is painstakeningly slow (without resorting to using Mac and Glyphs).

**Comment by benkiel** [comment]
Extractor extracts into a given UFO object. So, the library that provides the object handles the save.

You can see how Defcon handles it here: https://defcon.robotools.dev/en/latest/objects/font.html#defcon.Font.save

So, you'd do something like:
```python
>>> import extractor
>>> import defcon
>>> ufo = defcon.Font()
>>> extractor.extractUFO("/path/to/MyCJKFont.ttf", ufo)
>>> ufo.save("/path/to/MyFont.ufo", structure='zip')
```

**Comment by NightFurySL2001** [comment]
Thank you! Didn't notice it was in a separate package.
