### ISSUE TITLE
Request to provide command line interface program

### ISSUE THREAD

**Issue by NightFurySL2001** [robotools/extractor#60]
Will it be a good idea to introduce a command line program such as those provided in fontTools (eg. ttx, fonttools varlib.mutator), fontmake and AFDKO (eg. tx, sfntedit)? This allow beginners who just want to convert a font from binary to UFO to just install and run.

I have written one such program which might be useful: https://github.com/NightFurySL2001/py-fonttools-script/blob/main/convert_ufo.py

**Comment by benkiel** [comment]
See PR #35. I'll relook at this.
